<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "newscatinvite"
 *
 * Auto generated by Extension Builder 2014-05-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'News category invitation',
    'description' => 'Send invitations to let other users add news to their categories.',
    'category' => 'module',
    'author' => 'Jonas Renggli',
    'author_email' => 'jonas.renggli@visol.ch',
    'author_company' => 'visol digitale Dienstleistungen GmbH',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.999',
            'news' => '6.1.0-6.1.999',
        ],
        'conflicts' => [],
        'suggests' => [
            'roq_newsevent' => '3.3.0-3.99.99',
        ],
    ],
];
