<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "newscatinvite"
 *
 * Auto generated by Extension Builder 2014-05-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'News category invitation',
	'description' => 'Send invitations to let other users add news to their categories.',
	'category' => 'module',
	'author' => 'Jonas Renggli',
	'author_email' => 'jonas.renggli@visol.ch',
	'author_company' => 'visol digitale Dienstleistungen GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2',
			'fluid' => '6.2',
			'typo3' => '6.2',
			'news' => '3.1.0-3.99.99',
			'roq_newsevent' => '3.0.0-3.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
